server:
  port: 9900
  session-timeout: 1800
  context-path: /demo
  tomcat:
    uri-encoding: UTF-8

spring.datasource:
        name: demo
        url: jdbc:mysql://106.14.202.240:3306/iov
        username: root
        password: 1qaz2wsx
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.bean
  localCacheScope: statement
  cacheEnabled: true

spring.redis:
       host: 106.14.202.240
       port: 6379
       pool.maxActive: 8
       pool.maxWait: -1
       pool.maxIdle: 8
       pool.minIdle: 0
       timeout: 0
       database: 0

logging:
    level:
       com.ibatis:DEBUG
